apiVersion: v1 
kind: LimitRange 
metadata: 
  name: limits 
spec: 
  limits: 
  - default: 
      cpu: 400m
      memory: 50Mi
    defaultRequest: 
      cpu: 400m
      memory: 50Mi
    type: Container

