apiVersion: v1
kind: Pod
metadata:
  name: kiada-stdin-once
spec:
  containers:
  - name: kiada
    image: luksa/kiada:0.2
    imagePullPolicy: Always
    stdin: true
    stdinOnce: true
    ports:
    - containerPort: 8080
