apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec: 

  container: 
   - name: data-processor
     image: data-processor
  
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - Large
            - Medium
            - Small
