apiVersion: v1 
kind: Service
metadata: 
  name: myapp-service

spec: #this is were we are defining actual services
    type: NodePort
    ports:
      - targetPort: 80
        port: 80
        nodePort: 30008
    selector:
      app: myapp
      type: front-end
  