apiVersion: v1
kind: Pod
metadata:
  name: quote-poststart-fail
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - name: http
      containerPort: 80
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - "echo 'Emulating a post-start hook failure'; exit 1"
