apiVersion: v1
kind: Pod
metadata:
  name: kiada-liveness-fail-norestart
spec:
  restartPolicy: Never
  containers:
  - name: kiada
    image: luksa/kiada:0.1
    ports:
    - name: http
      containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 9999 # intentionally using wrong port to make probe fail
  - name: envoy
    image: luksa/kiada-ssl-proxy:0.1
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901
    livenessProbe:
      httpGet:
        path: /ready
        port: admin
      initialDelaySeconds: 10
      periodSeconds: 3
      timeoutSeconds: 2
      failureThreshold: 5
