apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-request-limit-ratio
spec:
  rules:
    - name: set-request-limit-ratio
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        - key: "{{ request.operation || 'BACKGROUND' }}"
          operator: AnyIn
          value:
            - CREATE
            - UPDATE
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - resources:
                  +(limits):
                    +(cpu): "{{ multiply('{{ request.object.spec.containers[0].resources.requests.cpu || \'0\' }}', '5') }}"
                    +(memory): "{{ multiply('{{ request.object.spec.containers[0].resources.requests.memory || \'0\' }}', '5') }}"
