apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: some-cluster-role
rules:
  - apiGroups:
      - '*'
    resources:
      - Service
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: some-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: some-cluster-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:masters
