apiVersion: v1
kind: Pod
metadata:
  name: mongodb-nfs
spec:
  volumes:
  - name: quiz-data
    persistentVolumeClaim:
      claimName: mongodb-claim
  containers:
  - name: mongodb
    image: mongo:5
    volumeMounts:
    - name: quiz-data
      mountPath: /data/db
