apiVersion: v1
kind: Pod
metadata:
  name: trouble-shooter
  labels:
    role: trouble-shooter
spec:
  nodeSelector:
    kubernetes.io/hostname: k3d-k3s-default-agent-1
  containers:
    - name: trouble-shooter
      image: g1g1/py-kube:0.3
      command: ["bash"]
      args: ["-c", "echo started...; while true ; do sleep 1 ; done"]

