apiVersion: v1
kind: Pod
metadata:
  name: kiada
spec:
  volumes:
  - name: pod-meta
    downwardAPI:
      items:
      - path: pod-name.txt
        fieldRef:
          fieldPath: metadata.name
  containers:
  - name: kiada
    image: luksa/kiada:0.4
    volumeMounts:
    - name: pod-meta
      mountPath: /pod-metadata


