apiVersion: v1
kind: Pod
metadata:
  name: kiada-ssl-args
spec:
  containers:
  - name: kiada
    image: luksa/kiada:0.1
    ports:
    - name: http
      containerPort: 8080
  - name: envoy
    image: luksa/kiada-ssl-proxy:0.1
    # NOTE: In envoy's Dockerfile, CMD is set to -c /etc/envoy/envoy.yaml;
    # by setting the args field here, we override the CMD and must specify
    # the path to the config file, otherwise envoy won't run
    args:
    - -c
    - /etc/envoy/envoy.yaml
    - --log-level
    - debug
    ports:
    - name: https
      containerPort: 8443
    - name: admin
      containerPort: 9901